---
title: "Permutation test on Spearman functional correlation coefficient"
output:
  pdf_document: default
  html_document: default
date: "2023-07-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r, include=FALSE}
rm(list=ls())

###Setting the working directory as the SOURCE FILE LOCATION
setwd("~/Documents/GitHub/Nonparametric-Statistics-project/src/Markdowns")

inputpath = "../data"
outputpath = "../data"

#Imports
library(tidyr)
library(dplyr)
library(lme4)
library(pbapply)
library(mgcv)
library(conformalInference)
library(ggplot2)
library(progress)
library(parallel)
library(pbapply)
library(roahd)


#Import data
data<-read.table("../../data/final_dataset_2007-2020.txt",
                 header=T, 
                 sep='',
                 check.names = FALSE)


data_spearman<-data[data$Year!='2007',c("Country","Year","GDP","Education",
                                        "Affordability","Cig_taxes",
                                        "Prevalence_both",
                                        "Prevalence_males",
                                        "Prevalence_females")]
#DO NOT FORGET TO LOG!
data_spearman$GDP<-log(data_spearman$GDP)
data_spearman_gdp<-data_spearman[,c("Country","Year","GDP")]
data_spearman_affordability<-data_spearman[,c("Country","Year","Affordability")]
data_spearman_cig<-data_spearman[,c("Country","Year","Cig_taxes")]
data_spearman_prevalence_b<-data_spearman[,c("Country","Year","Prevalence_both")]
data_spearman_prevalence_m<-data_spearman[,c("Country","Year","Prevalence_males")]
data_spearman_prevalence_f<-data_spearman[,c("Country","Year","Prevalence_females")]
data_spearman_education<-data_spearman[,c("Country","Year","Education")]
data_spearman_education_f<-data_spearman[,c("Country","Year","Education")]
```

First, Icreate the two functional data

```{r, include=FALSE}
#males
Prev_m_table <- data_spearman_prevalence_m %>%
  pivot_wider(names_from = Year, 
              values_from = Prevalence_males)

Prev_m_table<-t(as.data.frame(Prev_m_table))
colnames(Prev_m_table)<-Prev_m_table[1,]
Prev_m_table<-t(Prev_m_table[-1,])
#I need to reorganize in a table using dplyr
grid <-  seq( 2008, 2020, length.out =  7)
#transforming data into fd
f_data_prev_m <- fData(grid,Prev_m_table)

#Females
Prev_f_table <- data_spearman_prevalence_f %>%
  pivot_wider(names_from = Year, 
              values_from = Prevalence_females)

Prev_f_table<-t(as.data.frame(Prev_f_table))
colnames(Prev_f_table)<-Prev_f_table[1,]
Prev_f_table<-t(Prev_f_table[-1,])
#I need to reorganize in a table using dplyr
grid <-  seq( 2008, 2020, length.out =  7)
#transforming data into fd
f_data_prev_f <- fData(grid,Prev_f_table)

```

Utils
```{r}
diagnostic_permutation <- function(T20, T2) {
  B <- length(T2)
  
  # Compare real test statistic with the ones given by the permuted data
  hist(T2, xlim = range(c(T2, T20)))
  abline(v = T20, col = 3, lwd = 4)
  
  # Empirical cumulative distribution function
  plot(ecdf(T2),main="ECDF(T2)")
  abline(v = T20, col = 3, lwd = 4)
  
  # P-value
  p_val <- sum(T2 >= T20) / B
  cat("p-value: ", p_val)
}

compute_t_stat <- function(df1, df2,grid) {
  df1_f<- roahd::fData(grid,df1)
  df2_f<- roahd::fData(grid,df2)
  bivariate_data <-roahd::as.mfData(list(df1_f, df2_f))
  spearman_f<-roahd::cor_spearman(bivariate_data, ordering='MHI')
  return(abs(spearman_f))
}
```

Now I compute the Spearmann functional correlation coefficient

```{r}
# observed test statistics
df1<-Prev_m_table
df2<-Prev_f_table
T20 = compute_t_stat(df1, df2,grid)
T20
```

My T0 is 0.54, indicating moderate positive correlation

```{r}
perm_wrapper = function(df1,df2,grid) {
  df_pooled = rbind(df1, df2)
  n = nrow(df_pooled)
  n1 = nrow(df1)
  permutation = sample(n)
  df_perm = df_pooled[permutation, ]
  df1_perm = df_perm[1:n1, ]
  df2_perm = df_perm[(n1 + 1):n, ]
  compute_t_stat(df1_perm, df2_perm,grid)
}

seed=2022
B=1000
n_cores <- detectCores()
cl = makeCluster(n_cores)
invisible(clusterEvalQ(cl, library(DepthProc)))
clusterExport(cl, varlist = list("perm_wrapper", "df1", "df2", "grid", "compute_t_stat"))
set.seed(seed)
T2 <- pbreplicate(10000, perm_wrapper(df1, df2, grid), cl = cl)
stopCluster(cl)
```

```{r}
par(mfrow=c(1,2))
diagnostic_permutation(T20,T2)
```

P-value is 0, hence I can reject the null hypothesis of no functional correlation